apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-mock-app
spec:
  selector:
    matchLabels:
      app: java-mock-app
  replicas: 2
  template:
    metadata:
      labels:
        app: java-mock-app
    spec:
      containers:
        - name: java-mock-app
          image: odeliks/java-mock-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-mock-app-node-port
spec:
  type: NodePort
  selector:
    app: java-mock-app
  ports:
    - port: 8080
      targetPort: 8080